/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTopics"];
        put?: never;
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get: operations["getTopic"];
        put?: never;
        post?: never;
        delete: operations["deleteTopic"];
        options?: never;
        head?: never;
        patch: operations["updateTopic"];
        trace?: never;
    };
    "/topics/{topicId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get: operations["listFiles"];
        put?: never;
        post: operations["uploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/files/{fileId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/topics/{topicId}/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/tests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get: operations["listTopicTests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/tests/{testId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        get: operations["getTest"];
        put: operations["updateTest"];
        post?: never;
        delete: operations["deleteTest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/tests/{testId}/save": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/tests/{testId}/questions/{questionId}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
                questionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["regenerateQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/tests/{testId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSavedTests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /**
         * @description Server-sent events for one topic. Event names: `job.progress`, `job.succeeded`, `job.failed`,
         *     `file.status`, `message.created`, `topic.deleted`, `heartbeat` (every 15 s). `data` is JSON of
         *     `TopicEvent`. Supports `Last-Event-ID` for resume.
         */
        get: operations["topicEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "VALIDATION_FAILED" | "UNSUPPORTED_FILE_TYPE" | "AUTH_REQUIRED" | "TOKEN_EXPIRED" | "INVALID_CREDENTIALS" | "EMAIL_NOT_VERIFIED" | "FORBIDDEN" | "TOPIC_NOT_FOUND" | "FILE_NOT_FOUND" | "SESSION_NOT_FOUND" | "TEST_NOT_FOUND" | "JOB_NOT_FOUND" | "TOPIC_DELETING" | "FILE_NOT_READY" | "EMAIL_TAKEN" | "JOB_IN_PROGRESS" | "FILE_TOO_LARGE" | "TOPIC_QUOTA_EXCEEDED" | "TOPIC_STORAGE_EXCEEDED" | "NO_TEXT_EXTRACTED" | "GENERATION_INVALID" | "RATE_LIMITED" | "TOO_MANY_JOBS" | "LLM_UNAVAILABLE" | "CONSENT_REQUIRED" | "INTERNAL";
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                message: string;
                request_id: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Accepted: {
            /** @constant */
            status?: "accepted";
        };
        JobAccepted: {
            job_id: string;
        };
        /** @enum {string} */
        Language: "hu" | "en";
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            language: components["schemas"]["Language"];
            /** @constant */
            confirm_age_16: true;
            accepted_terms_version: string;
        };
        User: {
            id: string;
            email: string;
            language: components["schemas"]["Language"];
        };
        Session: {
            access_token: string;
            /** @description Seconds. */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        Me: components["schemas"]["User"] & {
            /** Format: date-time */
            created_at: string;
            usage: {
                topics: number;
                saved_tests: number;
            };
            limits: components["schemas"]["Limits"];
        };
        Limits: {
            /** @default 50 */
            max_topics: number;
            /** @default 20 */
            max_files_per_topic: number;
            /** @default 104857600 */
            max_topic_bytes: number;
            /** @default 20971520 */
            max_file_bytes: number;
            /** @default 10 */
            max_files_per_upload: number;
            allowed_types: string[];
        };
        TopicInput: {
            name: string;
            description?: string;
        };
        TopicPatch: {
            name?: string;
            description?: string;
        };
        Topic: {
            id: string;
            name: string;
            description: string;
            /** @enum {string} */
            status: "active" | "deleting";
            file_count: number;
            total_bytes: number;
            saved_test_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_activity_at: string;
            /**
             * Format: date-time
             * @description Deleted automatically after this much inactivity.
             */
            expires_at: string;
        };
        TopicList: {
            items: components["schemas"]["Topic"][];
            next_cursor: string | null;
            total: number;
        };
        /** @enum {string} */
        FileStatus: "queued" | "extracting" | "chunking" | "indexing" | "ready" | "failed";
        TopicFile: {
            id: string;
            topic_id: string;
            filename: string;
            mime: string;
            size_bytes: number;
            status: components["schemas"]["FileStatus"];
            error_code: components["schemas"]["ErrorCode"] | null;
            chunk_count: number;
            page_count?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        ChatSession: {
            id: string;
            topic_id: string;
            title: string;
            message_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        QuestionType: "mcq" | "tf" | "open";
        /** @enum {string} */
        Difficulty: "easy" | "medium" | "hard";
        GenerationOptions: {
            count: number;
            types: components["schemas"]["QuestionType"][];
            difficulty: components["schemas"]["Difficulty"];
            exam_language: components["schemas"]["Language"];
            /** @enum {string} */
            mode: "fast" | "thorough";
            /** @description Limit retrieval to these files. Omit for all ready files. */
            file_ids?: string[];
        };
        MessageInput: {
            content: string;
            /** @enum {string} */
            intent: "generate" | "ask";
            options?: components["schemas"]["GenerationOptions"];
        };
        Message: {
            id: string;
            session_id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            job_id: string | null;
            test_id: string | null;
            options?: components["schemas"]["GenerationOptions"];
            citations?: components["schemas"]["Citation"][];
            error_code?: components["schemas"]["ErrorCode"] | null;
            /** Format: date-time */
            created_at: string;
        };
        MessageList: {
            items: components["schemas"]["Message"][];
            next_cursor: string | null;
        };
        Citation: {
            file_id: string;
            chunk_id: string;
            filename?: string;
            page?: number | null;
            snippet?: string;
        };
        Answer: {
            text: string;
            is_correct: boolean;
        };
        Question: {
            id: string;
            type: components["schemas"]["QuestionType"];
            text: string;
            answers: components["schemas"]["Answer"][];
            citations: components["schemas"]["Citation"][];
            difficulty: components["schemas"]["Difficulty"];
        };
        Exam: {
            title: string;
            questions: components["schemas"]["Question"][];
        };
        TestSummary: {
            id: string;
            topic_id: string;
            session_id: string | null;
            title: string;
            question_count: number;
            saved: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Test: components["schemas"]["TestSummary"] & {
            exam: components["schemas"]["Exam"];
        };
        ExportRequest: {
            /** @enum {string} */
            format: "pdf" | "pdf_with_key" | "moodle_xml" | "gift" | "json";
            /**
             * @default 1
             * @enum {integer}
             */
            variants?: 1 | 2;
            /** @default false */
            shuffle_answers?: boolean;
        };
        /** @enum {string} */
        JobType: "ingest_file" | "generate_test" | "answer_question" | "regenerate_question" | "delete_topic" | "export_account" | "delete_account";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        Job: {
            id: string;
            type: components["schemas"]["JobType"];
            topic_id: string | null;
            status: components["schemas"]["JobStatus"];
            /** @description e.g. retrieving, generating, validating, extracting, indexing */
            stage: string | null;
            progress: number;
            queue_position: number | null;
            error_code: components["schemas"]["ErrorCode"] | null;
            result: {
                test_id?: string;
                file_id?: string;
                message_id?: string;
                download_url?: string;
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Payload of an SSE `data:` line. Which fields are set depends on the event name. */
        TopicEvent: {
            job?: components["schemas"]["Job"];
            file?: components["schemas"]["TopicFile"];
            message?: components["schemas"]["Message"];
            topic_id?: string;
        };
    };
    responses: {
        /** @description Error envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TopicId: string;
        FileId: string;
        SessionId: string;
        TestId: string;
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Verification e-mail sent. Same answer whether or not the address exists. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description E-mail verified. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in. Sets the `mimir_refresh` HttpOnly cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token (refresh cookie rotated). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh token revoked and cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Reset e-mail sent if the account exists. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            429: components["responses"]["Error"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password changed; all sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Account deletion started (GDPR Art. 17). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    language?: components["schemas"]["Language"];
                };
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    exportMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export job started (GDPR Art. 15/20). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    listTopics: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cascade delete started (key destroyed first). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicPatch"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files of the topic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TopicFile"][];
                    };
                };
            };
        };
    };
    uploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    "files[]": string[];
                    /** @description Must be true — the user confirms they may upload these documents. */
                    consent: boolean;
                };
            };
        };
        responses: {
            /** @description Files queued for ingestion. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: components["schemas"]["TopicFile"][];
                        job_ids: string[];
                    };
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    retryFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion restarted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ChatSession"][];
                    };
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session and its unsaved tests deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                };
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    listMessages: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Message stored, generation queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: components["schemas"]["Message"];
                        job_id: string;
                    };
                };
            };
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    listTopicTests: {
        parameters: {
            query?: {
                saved?: boolean;
            };
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tests of the topic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TestSummary"][];
                    };
                };
            };
        };
    };
    getTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test with questions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Test"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    exam: components["schemas"]["Exam"];
                };
            };
        };
        responses: {
            /** @description Saved edits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Test"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    deleteTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as saved (opt-in retention). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Test"];
                };
            };
        };
    };
    regenerateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regeneration queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    exportTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description The exported file (Content-Disposition carries the file name). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/zip": string;
                    "application/xml": string;
                    "text/plain": string;
                    "application/json": string;
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listSavedTests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All saved tests grouped by topic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        groups: {
                            topic: {
                                id: string;
                                name: string;
                            };
                            tests: components["schemas"]["TestSummary"][];
                        }[];
                    };
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Job"][];
                    };
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    topicEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
